app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #32 
Changes: App does not crash after pressing send button multiple number of times when there is no device connected. A toast is shown.

fix: App does not crash after pressing send button multiple number of times.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #45 
Changes: When the send button is clicked, the keyboard goes down automatically. When the edit text is pressed again, the keyboard pops up again.

fix: Keyboard goes down when send button is pressed.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
app/src/main/res/layout/spinner_item.xml

Fixes #36 
The issue is becasue of the usage of default android simple spinner item layout. So instead of that, a custom spinner item layout is made with the width till the end, making the items easier to click.

fix: Spinner item's width is not till the end

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #67 
Changes: 
Now, keyboard would close whenever the send button is clicked, even when bluetooth is off.

fix: Close keyboard whenever send button is clicked

---

app/src/main/res/layout/message_activity.xml

Fixes #69 
Changes: 
Added ScrollView. Now the send button can be accessed easily when the screen is rotated and also when the keyboard is open.

fix: Send option not accessible on screen rotation

---

app/build.gradle
app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
app/src/main/res/drawable/ic_led.xml
app/src/main/res/drawable/ic_led_lit.xml
app/src/main/res/layout/message_activity.xml
app/src/main/res/values/strings.xml

Fixes #14 
Motive : Implement a badge preview on the top of the screen
Changes: 
- Created a Custom View (PreviewBadge.kt) for getting the complete visual of an Actual LED
- Added seperate data classes(Cell.kt, CheckList.kt) for better management
- Changes to MessageActivity to incorporate Support for Badge
- Vector Drawable's for LED
- Added Function in Presenter(MessagePresenter.kt) to take care of the hex conversions
- Changes to Message Activity XML
Screenshots of the changes:

To Implement a badge preview on the top of the screen

---

app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt

Fixes #17 
Changes: 
- a singleton to convert drawable to hex arrays

Code to Convert any 40x11 Translucent Gray-Scaled Bitmap to Hex Arrays

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
app/src/main/res/values/strings.xml

Fixes #42 
Changes: A toast is shown if no compatible device is found after scanning.

fix: A toast is displayed when no device is found.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #74 
Changes: The send button is now disabled for 10s after being clicked and is then enabled again instead of being non-clickable.

fix: Button disabled instead of being non-clickable.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #57 
Changes: The user can now exit the app by pressing exit in the dialog if the user does not want to provide Bluetooth permission.

fix: Added option to exit the app 

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
app/src/main/res/layout/message_activity.xml

Fixes #108 
Changes: 
- added onMeasure to always match the ratio provided

fix: the preview widget now maintains it's ratio according to the resolution

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #140 
Changes: If edittext is empty, the loader is still switched on the default bitmap is sent to the device,

fix: App crash when edittext is empty

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Fixes #126 
Changes: 
- onMeasure now calculates the height according to the width, irrespective of the originalHeight ( This fixes the Lollipop and below API issue as onMeasure use to return heightMeasuredSpec as 0)
- offsetToAdd should be different than the global offset for the widget as it usually did not make the cells in the center of the widget.

fix: maintaining ratio logic and some fixes in preview badge

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Details:
- Remove long redundant code on setting MODE
- Set the boolean logic for flash so that other animation can works with flash. The boolean flashLEDOn means that when that flag is set to true, the LED works normally, otherwise, all LED is turned off.This flag is only changed when user set pick the ifFlag option
Fixes: #132
This is the screenshot for RIGHT, other MODE I have tested and it also works fine. The GIF is a little bit unclear on blinking because I think it is already be compressed and some of the frame is cut out.

fix: Enable flash on left/right/up/down animation

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Detail:
- Currently, valueAnimator is set to default value 8800 so if a text (Ex: length = 80) is longer than the badgeWidth (44) then only the first 44 unit of the text is accessed when calling onDraw(). Change configValueAnimation by the length of the text/drawable so that when some text is longer than the screen, the onDraw() function will loop all the length of the text
- Remove redundant code
- Set up logic to make Move (UP,DOWN,LEFT,RIGHT) goes all of the screen. Flash and Marquee still works fine
Fixes: #144

fix: make animation on right/left/up/down goes all the way

---

app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #141 
Changes: If the edit text is empty, the default image bitmap image is shown in the preview if clicked by the user.

fix: Made the default bitmap image appear as preview.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
app/src/main/res/values/strings.xml

Fixes #97 
Changes: The app does not crash when a non-implemented character is previewed and a toast is shown.

fix: Prevented the app from crashing when a non-implemented character is entered.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Fixes #155 
Changes: 
- checking diff is removed so that we get the extra checks which act as a padding for the second list.
- adjusting the offsets after adding the padding and checking with the changed offsets of the list

fix: animation issues with left/right animation

---

app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt

Fixes #164 
Changes: 
- separate the logic of changing card background to viewholder
- changing card backgrounds using `notifyItemChanged` which doesn't update the whole list
- applying kotlin code practices

chore: refractor drawable adapter

---

app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/ScanHelper.kt

Fixes #165 
Changes:
- Change logic from `if(!isScanning)` to `if(isScanning)`
**ScreenShot**
Scan is perfomed . And result is shown now
**Logs before change**
Scan is not being perfomred
```
2019-04-06 13:15:00.328 30555-30555/com.nilhcem.blenamebadge I/MessagePresenter: ByteData: [77616E67000000000400000000000000, 00050000000000000000000000000000, 000000000000E304060D0F0000000000, 00000000000000000000000000000000, 001E3121033B67430D18133E7F9C082A, 9CFFFFFFFF7F003CC64260EEF3E1D88C, 640000020103060F0B0A010000000810, F8ECFEFA0AB000000000000000000000]
2019-04-06 13:15:00.511 30555-30563/com.nilhcem.blenamebadge I/em.blenamebadg: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
```
**Logs after change**
Scan …

fix: scan logic

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Fixes #159 
Changes: 
- onAttackWindow re-configuration cause the animation to reduce the width by 1/2

fix: animations go on the wrong side of the screen

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #101 
Changes: 
- we lock the screen rotation before the intent starts
- we unlock the screen rotation when intent is complete
Additional Context
This bug has been since android 2.2 ( https://issuetracker.google.com/issues/37114831 ). This is a workaround until the android team fixes it

fix: multiple bluetooth dialogs on rotation 

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt

Fixes #184 
Changes:
- Added Listeners for Checkboxs
- Added Listeners for Spinners
Screenshots for change:

fix: spinners and checkbox now trigger automatic preview

---

app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
app/src/main/java/com/nilhcem/blenamebadge/device/model/DataToSend.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
app/src/main/res/layout/message_activity.xml
app/src/main/res/values/strings.xml

Fixes #134 
NOW, you can play with another LED Effect on your badges.
Changes:
- Improved DataToSend According to the invertedLED
- We now check the invertedLED Check before preview and sending 
- All the hexadecimal to binary conversions are shifted to Converters.kt

feat: Inverted LED Effect

---

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
app/src/main/java/com/nilhcem/blenamebadge/util/KeyboardUtils.kt

Fixes #186 
Fixes #109
Changes: Keyboard now pops up automatically when shifting to text mode.

fix: Made keyboard appear automatically when shifting to text mode.

---

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt

Fixes #152 ( Checked Snowflake)
Changes: 
- the padding with `val diff = (badgeWidth - (oneByte * allHex.size)) / 2` now relies on `Mode.SNOWFLAKE`
- Added Algorithm for Snowflake Animation 

feat: Add Snowflake Animation Mode

---

app/src/main/res/layout-land/message_activity.xml

Fixes #168 
Changes: 
Made preview of the badge fixed in portrait mode for the ease of the user. Although it works as it was in the landscape mode. 

Make preview screen scrollable in landscape mode

---

app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainSavedFragment.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainTextDrawableFragment.kt
app/src/main/res/layout/fragment_main_save.xml
app/src/main/res/layout/fragment_main_text.xml

Details:
- App crashes because when the screen is rotated, the recycler view is destroyed. This is avoided by setting retainInstance to true in the onCreate() of the fragment
- Changing same id name for different recyclerView
- Currently, saving a configuration is in onPostExecute() of the AsyncTask class, which means that action saving is done in the main thread. I put it back into the doInBackground()
Fixes: #211

fix: Avoid app crash on saving after screen rotation

---

app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/MainSavedFragment.kt
app/src/main/res/values/strings.xml

Fixes #215 
Changes: When a saved configuration is deleted, the preview is cleared and a toast is displayed.

fix: If the selected item is deleted, preview is cleared and a toast is displayed

---

app/src/main/java/com/nilhcem/blenamebadge/util/StorageUtils.kt

Fixes: #253
It crashes due to NullPointerException from files variable

fix: App crash on installing

---

app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedFragment.kt
app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt

Fixes #280 
Changes:
- viewholder is attached to the activity instead of fragments

fix: retain items on rotate

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/shortcuts.xml

Fixes #308 
Changes: App shortcuts have been added to directly access saved badges or create badges modes.

feat: App shortcuts added

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
app/src/main/res/values/strings.xml

Fixes #351
Changes: Bluetooth permission is now asked only when the user presses the transfer button and not on opening the app.

feat: Bluetooth permission is asked when user presses the transfer button

---

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt

Changes: Replaced `context` with `requireContext()` as it is better for use in fragments. `context` might return a null value, but `requireContext()` will never return a null value.

chore: Replaced context with requireContext

---

app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt

fix: badge seems to cut off on devices with 19.5:9 ratio

---

app/src/main/res/layout/fragment_main_textart.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #390
Changes:
- Removed Unused Resources

chore: removed unused resources

---

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Fixes #411 
Changes: A toast notification is shown when a badge is saved.

feat: Added toast when a badge is saved

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt

Fixes #413 
Changes: Bluetooth will not be turned off automatically when the drawer activity is destroyed.

fix: Prevented bluetooth form closing automatically when drawer activity is destroyed.

---

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt

Fixes #416
Changes: 
- Added Permission Check Before saving badge

fix: force stop when rejected permission

---

scripts/prep-key.sh
scripts/upload-apk.sh

chore: Improve APK Names

---

.travis.yml
app/build.gradle
build.gradle
scripts/upload-apk.sh

Fixes #427 
Changes:
- Updated Upload Script

chore: added aab support and improved script

---

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt

Fixes #431 
Changes: 
- improved naming scheme for viewmodel
- fragment should share viewmodel

fix: retain fragment info when orientation changed

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt
app/src/main/java/org/fossasia/badgemagic/bindings/EditBadgeViewBindings.kt
app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedClipartFragment.kt
app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
app/src/main/java/org/fossasia/badgemagic/viewmodels/EditClipartViewModel.kt
app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
app/src/main/res/layout/activity_edit_clipart.xml
app/src/main/res/layout/recycler_item_saved_clipart.xml

Fixes #420
Changes:
- Ability to Edit Badges

feat: ability to edit badges

---

.travis.yml
Gemfile
fastlane/Fastfile
scripts/upload-apk.sh

Fixes #455 
Changes: 
- improved scripts and fastlane usage

chore: improved fastlane usage and scripts

---

.travis.yml
scripts/upload-apk.sh

chore: improved build scripts with deploy

---

README.md

chore: updated readme with creative emoticons

---

app/src/main/res/values/dimens.xml

Fixes #481
Changes
- fixed dimens for buttons

feat: Improve Edit Clipart Screen - Size and Buttons

---

.travis.yml
app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
versions.gradle

Fixes #498 
Changes: target api to 29

chore : changed target api to 29

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt
app/src/main/res/drawable/ic_folder_open_black_24dp.xml
app/src/main/res/menu/open_folder.xml

Fixes #479 Edit Badge Screen / Edit Clipart Screen
Add an "Open Folder" icon to the edit badge/edit clipart screen on the top right of the screen on the menu bar. The icon should open "Saved Badges" / "Saved Cliparts".
EditBadgeScreen:-
EditClipartScreen:-

feat: added shortcut to open saved activities from edit activities

---

app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
app/src/main/java/org/fossasia/badgemagic/database/StorageFilesService.kt
app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/DrawFragment.kt
app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt

Fixes #544 Shift to App-Specific Directory for storing Badge and Clipart's

feat: app specific directory storage

---

app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt
app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt

Fixes #528 
Changes: The clipart list in viewmodel was not populated. So, I created another method in the viewmodel that populates the list from the adapter. Now, the clipart is getting deleted without any crash.

fix: Resolve delete cliparts issue

---

app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt

fix: reverse listing of saved badges

---

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt

Fixes #527 
Changes: The issue was due to not slicing the string in a proper way. In the onTextChanged method of the listener, I have changed the implementation to update the string without the text of the deleted clipart and instead of calling the setPreview method in the onTextChanged, it's being called in afterTextChanged method, which makes more sense.

fix: Resolve intermediate clipart delete issue

---

app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt
app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt

Fixes #577 
if I insert clipart in order 1 2 3 4 then this is how it displays (according to date of creation or modification)
also when a user updates or edits it then display according to date of last modification.

fix: uneven clipart listing

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt

Fixes #579 
Changes: Used a new function hideKeyboard in onDrawerOpened method of the nav drawer to hide the keyboard automatically when the drawer opens.

fix: Resolve keyboard visibility issue

---

app/src/main/java/org/fossasia/badgemagic/di/Modules.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
app/src/main/java/org/fossasia/badgemagic/util/BluetoothAdapter.kt
app/src/main/java/org/fossasia/badgemagic/util/BluetoothManager.kt

feat: feature to turn bluetooth on

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt

Fixes #594 
Changes: The issue was with the intent action condition. It was earlier defined that if the action is MAIN then open TextArtFragment and every action is by default is MAIN so I just removed that condition and now it's working perfectly.

fix: Resolve drawer selection issue in draw clipart fragment

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt
app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt
app/src/main/java/org/fossasia/badgemagic/util/BluetoothAdapter.kt

fix: location issue with sending badges

---

app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt

fix: app launch issue

---

android/src/main/res/menu/drawer_items.xml

Fixes #614  
Changes: 
Removed about us from unchecked section where the item checked state was not imp (eg. Share, buy )

feat: about us selection in drawer

---

android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values/strings.xml

Fixes #[619]
Changes: Corrected delete messages for both languages, similar to that of saved badge message.

fix: Semantic changes for delete confirmation message
