fossasia/badge-magic-android

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> chore: Upgrade plugin version to 3.1.4 

.travis.yml
=> feat: setup travis CI

app/build.gradle
=> fix: travis CI

scripts/prep-key.sh, scripts/upload-apk.sh
=> feat: add scripts to configure build of apk branch

.travis.yml
=> Update travis CI to run apk scripts 

.travis.yml, README.md
This PR is intentionaly send to check the working of auto build of apk files due to #8
=> [WIP]chore: Update README.md

app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
Fixes #13 
App name has been changed to Badge Magic. Colors have also been updated and made similar to pslabs red colors.
Screenshots of the change :
=> Fix for issue #13 : App name changed to Badge Magic and colors updated.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add issue and pull request template

.travis.yml, app/build.gradle, app/src/main/java/com/nilhcem/blenamebadge/core/android/viewbinding/Kotterknife.kt, app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt, app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/Constants.kt, app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/GattClient.kt, app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/ScanHelper.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/test/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverterTest.kt
=> chore: Add spotless check for kotlin

.travis.yml, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Fixes #41 
Changes: gradle plugin version has been updated along with other dependencies.
=> chore: Update gradle plugin version and other dependencies.

app/src/main/res/layout/spinner_item.xml
Fixes #81
Changes: Color has been changed to black as it was earlier.
=> fix: Made the color of the text views black again.

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Fixes #90 
Changes: 
- Changed the way offsets were calculated
- Changed the way BgBounds were calculated
=> Changed the way offsets were calculated for the background and the cells inside custom view

app/build.gradle, app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt, app/src/main/java/com/nilhcem/blenamebadge/data/DrawableInfo.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt, app/src/main/res/layout/message_activity.xml, app/src/main/res/layout/recycler_item.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fixes #17 
Changes: 
- RecyclerView to display all the drawables in cards
- Adapter Configured to select only one option
- Preview Button for Bitmaps
- Used the Code in PR #89 to Convert Drawable's and Display them on the preview Badge
=> feat: Feature to display Bitmap

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Implemented the Four Basic Animations
Fixes #93 
Changes: 
- Added Animations for Modes, with Speed Control, which also includes Features of Marquee and Flash
- ValueAnimator Manages the Values for the animation
- Control Is Based on the Type of the animation mode from now
Special Thanks to @yashk2000 for providing me the exact hardware animations
=> feat: Animations in LED Badge Preview

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Changes:
- Added the rest of parameters while calling setValue() in MessageActivity
=> fix: Added missing parameters in setValue Function

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Fixes #83 
Changes: [Add the prepare scan method which is calling the bluetooth request]
=> Fix #83 request for bluetooth

app/build.gradle, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/res/layout/message_activity.xml
Fixes #49 
Changes:
Added spinner while sending bits to the device.
=> Add spinner while sending bytes to the device

README.md
Fixes: #123 
Changes: Updated communication section in Readme.md for badge-magic gitter channel.
=> chore: added badge-magic gitter channel

app/src/main/java/com/nilhcem/blenamebadge/device/bluetooth/ScanHelper.kt
Detail:
Only enable startScan function if isScanning flag is false
Fixes: #129
=> fix: app crash on clicking send while scanning

app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt, app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt
Fixes #154
Changes: 
- Removed Any which ultimately removed the extra casting
- All Arraylist are changed to mutableList
- convertImageToLEDHex now does not check for the black value, any value other than transparent is considered black, this removes the restriction of only grayscaled images
=> fix: remove code smells from app and bug fixes

.travis.yml, app/build.gradle, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Fixes #148
Changes: 
- Added a singleton class to hold the state values when the events onSaveInstanceState and onRestoreInstanceState are fired
=> fix: save state of preview badge, updated sdk's in build gradle to the latest available

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Changes:
- Typo Error of last PR
=> fix: typo in bundle key

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Fixes #110 
Changes:
Both checkbox are now enabled at the same time.
=> fix: Enabling both chekbox at a same time

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/res/values/strings.xml
Fixes #172 
Changes: App can be used even if Bluetooth is enabled or not
=> feat: app can be used without bluetooth

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Partially Fixes: #152 (Animation is Checked in the Task List)
Changes: 
- countFrame, lastFrame now further divide the animation into two more steps.
- So we look for not similar frames and update the lastFrame accordingly.
- The Animation is now divided into further 3 parts: 
* First Phase `countFrame < (badgeWidth / 2)`
* Second Phase `countFrame < (badgeWidth / 2) & countFrame >  3*(badgeWidth / 2)`
* Third Phase `countFrame > 3*(badgeWidth / 2)`
- Next we check the lines and the rows lying in that range and we get the desired animation
=> feat: Animation Mode in Preview

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Fixes #152 
Changes: 
- Added Laser Animation
- Made Conditions more readable
=> feat : Added Laser Animation and made conditions more readable

app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/res/layout/message_activity.xml, app/src/main/res/values/strings.xml
Fixes #151 
Fixes #168 
Fixes #169
Fixes #170 
Fixes #136 
Fixes #114
Changes:
- Radio buttons have been added to choose between text and drawables.
- Preview button has been completely removed. The preview badge is continually updated as the user keeps changing data.
Screenshots/GIF for the change:
=> feat: Radio buttons for text and drawable.

app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt, app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapDataToSend.kt, app/src/main/java/com/nilhcem/blenamebadge/device/model/BitmapMessage.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt
Changes: 
- Created Separate Data Classes to Handle Bitmap Operations
- convertBitmap function is completely new and handles the data according to the bitmaps
- getFlash, getOptions, getSize, getMarquee are created according to the BitmapData now
- getMessages now calculates the ByteArray with a completely new logic. 
- All Functions are made to support bitmaps.
Screenshots:
NOTE: As I do not own the hardware yet, @yashk2000 can you please send the actual hardware screenshots to ensure that everything works. Please add it to the review itself
=> feat: added core changes to send drawable to actual device

app/build.gradle, app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt, app/src/main/java/com/nilhcem/blenamebadge/device/model/Mode.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/util/Converters.kt, app/src/main/res/layout/message_activity.xml, app/src/main/res/layout/recycler_item.xml, build.gradle
Fixes #188 
Changes: 
- Updated to AndroidX
- Updated Kotlin Version to 1.3.30
=> chore: migrated to android jetpack

app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt
Fixes #200 
Changes: Loader is now displayed on pressing the send button.
=> fix: Loader will be displayed on clicking send.

app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt, app/src/main/res/color/navigation_item.xml, app/src/main/res/drawable/ic_bottom_bar_saved.xml, app/src/main/res/drawable/ic_bottom_bar_text.xml, app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/navigation.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fixes #208 
Changes:
- Added a BottomBar for navigation between fragments
=> feat: Bottombar for navigation between fragments

app/src/main/java/com/nilhcem/blenamebadge/device/DataToByteArrayConverter.kt
Fixes #98 
Changes: More symbols have been implemented in the app.
=> feat: Added 8 new symbols

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt, app/src/main/res/layout-land/fragment_main_text.xml, app/src/main/res/layout-land/recycler_save_item.xml, app/src/main/res/layout/dialog_save.xml, app/src/main/res/layout/fragment_main_save.xml, app/src/main/res/layout/fragment_main_text.xml, app/src/main/res/layout/recycler_item.xml, app/src/main/res/layout/recycler_save_item.xml, app/src/main/res/values/dimens.xml
Details:
- Add horizontal variations for saved configurations view, main activity view
- Extract resources
Fixes: #209
=> feat: Add horizontal variations

app/src/main/res/layout-land/fragment_main_text.xml
Fixes #224 
Changes: 
- id was changed in the last merges, fixed according with the new name
=> fix: app crash on rotation

app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
Fixes #220
Changes: 
- separated `ensureBluetoothEnabled()` from `prepareScan()` 
- fab listener is set according to the bluetooth state
=> fix: viewpager not initializing when bluetooth not enabled

app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt
Fixes #152 
Changes:
- Created Algorithm for Picture Animation
- Fixed Ratio issue
=> feat: Picture Animation Mode

app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt
Fixes #214 
Changes: Keyboard goes down when shifting to saved mode.
=> fix: Keyboard goes down when shifting to saved mode.

app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/main/MainNavigator.kt, app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout-land/fragment_main_text.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_main_text.xml, app/src/main/res/values/strings.xml
Fixes #235 
Changes:
- Removed Floating Button completely
- Added a Transfer Button on the Right of the send button
- Made BottomBar Invisible for now
=> fix: added a transfer button on the right of send button 

app/src/main/AndroidManifest.xml, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt, app/src/main/res/layout-land/fragment_main_text.xml, app/src/main/res/layout/fragment_main_text.xml, app/src/main/res/layout/sections_tab.xml
Fixes #248 
Changes: 
- Added a Tablayout which switches between Effects, Animation and Speed
=> enhancement : Improve and Simplify UI and Colors

app/src/main/res/layout-land/activity_main.xml, app/src/main/res/layout-land/fragment_main_text.xml, app/src/main/res/layout/fragment_main_text.xml, app/src/main/res/layout/sections_tab.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #250 
Changes: All names now just have the first letter capitalized. Space between send/transfer buttons and the section above has also been increased.
=> enhancement: Avoided capitalizing all letters and increased space between buttons.

app/src/main/res/layout/fragment_main_text.xml
Fixes #255
Changes:
- Moved the layout inside the scrollview
=> fix : Layout Overlap Fix

app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeAdapter.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt, app/src/main/res/layout/effects_layout.xml, app/src/main/res/menu/save_menu.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Fixes #250 
Changes: All existing Upper case strings have been made lower case with only the first letter capital. 
=> enhancement: Replaced all upper case names

app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableItemHolder.kt, app/src/main/java/com/nilhcem/blenamebadge/adapter/ModeItemHolder.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt, app/src/main/res/drawable/round_corner_bg.xml, app/src/main/res/layout-land/fragment_main_text.xml, app/src/main/res/layout/fragment_main_text.xml, app/src/main/res/layout/recycler_item.xml, app/src/main/res/values/dimens.xml
Fixes #240
Changes:
- Clipart section is now a list with 6 columns
=> feat : Implement Clipart (Drawables) dropdown area

app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerActivity.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_saved/MainSavedFragment.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableFragment.kt, app/src/main/java/com/nilhcem/blenamebadge/ui/fragments/main_text/MainTextDrawableViewModelProviderFactory.kt, app/src/main/java/com/nilhcem/blenamebadge/util/InjectorUtils.kt
Fixes #275 
Changes: The app does not crash now on opening.
=> fix: Prevented app from crashing when opened.

app/src/main/java/com/nilhcem/blenamebadge/ui/custom/PreviewBadge.kt
Fixes #278 
Changes:
- We now don't define the valueAnimator anonymously
=> fix: Memory Leak

app/build.gradle, build.gradle, versions.gradle
Fixes #289 
Changes: 
- Added Leak Canary Library
- Optimize gradle file
=> refactor: added leak canary and optimize gradle

app/src/main/java/com/nilhcem/blenamebadge/ui/drawer/DrawerActivity.kt
Fixes #285 
Changes: 
- Disable Bluetooth when destroying app
=> fix: disable bluetooth when closing app

app/build.gradle, build.gradle, versions.gradle
Fixes #297 
Changes:
- Updated Versions
=> chore: bump gradle versions

app/build.gradle, app/src/main/java/org/fossasia/badgemagic/ui/AppViewModel.kt, app/src/main/java/org/fossasia/badgemagic/ui/AppViewModelProviderFactory.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_text/MainTextDrawableViewModelProviderFactory.kt, app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Fixes : #301
Changes: 
- Updated spotless kotlin
=> chore: Updated spotless kotlin

app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_saved/MainSavedFragment.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/main_text/MainTextDrawableFragment.kt
Fixes #300 
Changes: 
- declared all the listeners inside maintextfragment and stopped them accordingly
- removed rootview instance as it caused a major leak in every fragment
=> fix: memory leak in fragments

app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Fixes #311
Changes: 
- Listener removed ondetach
=> fix: memory leak in preview badge

app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
Fixes #312 
Changes:
- Fixed conditions for shortcuts
=> fix: shortcut drawer selected item

app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Fixes #314
Changes: 
- Improved Preview Badge class
=> refactor: preview badge

app/src/main/java/org/fossasia/badgemagic/ui/drawer/DrawerActivity.kt
Fixes #305 
Changes:
- Removed fade animation
=> fix: slow transitions when opening screens

versions.gradle
Fixes #320 
Changes:
- updated library
=> chore: update leak canary to alpha 2

app/src/main/java/org/fossasia/badgemagic/ui/custom/knob/OnCrollerChangeListener.java, app/src/main/java/org/fossasia/badgemagic/ui/custom/knob/OnCrollerChangeListener.kt
Fixes #323 
Changes: 
- converted file to kotlin
=> fix: converted java file to kotlin

app/src/main/java/org/fossasia/badgemagic/data/device/model/Mode.kt, app/src/main/java/org/fossasia/badgemagic/data/device/model/Speed.kt, app/src/main/java/org/fossasia/badgemagic/util/MoshiUtils.kt
Fixes #317 
Changes: 
- Created Adapters for Enums
=> fix: moshi adapter issue in release builds

scripts/prep-key.sh, scripts/upload-apk.sh
Changes: 
- Initial try for automatic release
=> chore: automatic signed release

scripts/prep-key.sh, scripts/upload-apk.sh
Changes: 
- Changes to condition
=> chore: updated conditions in automatic release scripts

scripts/upload-apk.sh, versions.gradle
Changes:
- Updated Conditions and Bumped up gradle version
=> chore: Updated Conditions and bumped up minSDK

app/src/main/java/org/fossasia/badgemagic/adapter/DrawableItemHolder.kt, app/src/main/java/org/fossasia/badgemagic/adapter/ModeItemHolder.kt, app/src/main/java/org/fossasia/badgemagic/util/Converters.kt, app/src/main/java/org/fossasia/badgemagic/util/Resource.kt
Fixes #337 
Changes: 
- Changed All deprecated functions to use resourcehelper
=> chore: remove deprecated getDrawable method

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/TextArtViewModel.kt, app/src/main/res/drawable/ic_clipart.xml, app/src/main/res/layout-land/fragment_main_textart.xml, app/src/main/res/layout/fragment_main_textart.xml
Fixes #339 
Changes:
- Added a Clipart button
=> fix: Do not show emoticons always

app/src/main/java/org/fossasia/badgemagic/data/device/bluetooth/GattClient.kt
Fixes #50 
Changes: 
- Added a Check for Null Exception
=> fix: NULLPointerException , when characterstics is null

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/res/values/strings.xml
Fixes #203 
Changes: 
- Added a Check before sending to check if it is empty
=> fix: Issue when edittext is empty and send is clicked

app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/res/drawable/ic_clipart.xml, app/src/main/res/drawable/ic_clipart_switcher_disabled.xml, app/src/main/res/drawable/ic_clipart_switcher_enabled.xml, app/src/main/res/layout-land/fragment_main_textart.xml, app/src/main/res/layout/fragment_main_textart.xml
Fixes #354
Changes:
- improved emoji in text fragment
=> enhancement: changed clipart switcher icon

app/src/main/res/layout/sections_tab.xml, app/src/main/res/values/dimens.xml
Fixes #353 
Changes: 
- improved layout to fit text in center
=> enhancement: Center speed button, add number in the button

app/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
Fixes #370 
Changes:
- Updates to Preview Badge
=> fix: Morphing Issues with Preview Badge

app/src/main/res/layout-land/fragment_main_textart.xml, app/src/main/res/layout/fragment_main_textart.xml
Fixes #355 
Changes:
- imeOptions does not show enter now
=> fix: Only allow oneliners

app/build.gradle
=> chore: Release v1.2.0

app/src/main/java/org/fossasia/badgemagic/adapter/DrawableItemHolder.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/res/layout/recycler_item.xml, app/src/main/res/values/dimens.xml
Fixes #384 
Changes:
- Changed Columns to 9
=> enhancement: changed column number to 9

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Fixes #391 
Changes:
- Translated Strings to Chinese
=> chore: translate strings to chinese for next release

.travis.yml
Fixes #398 
Changes:
- Removed Before Script
=> chore: remove before-install script 

app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt, app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt, app/src/main/java/org/fossasia/badgemagic/bindings/SavedClipartsViewBindings.kt, app/src/main/java/org/fossasia/badgemagic/data/SavedClipart.kt, app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt, app/src/main/java/org/fossasia/badgemagic/di/Modules.kt, app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt, app/src/main/java/org/fossasia/badgemagic/ui/custom/SquareImageView.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedClipartFragment.kt, app/src/main/java/org/fossasia/badgemagic/util/ImageUtils.kt, app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt, app/src/main/res/drawable/ic_draw_delete.xml, app/src/main/res/layout/fragment_saved_cliparts.xml, app/src/main/res/layout/recycler_item_saved_clipart.xml, app/src/main/res/menu/drawer_items.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fixes #405
Changes: 
- Added Option to show saved cliparts
In Drawer: 
Section:
=> feat: ability to show badges

app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt, app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt, app/src/main/java/org/fossasia/badgemagic/ui/custom/SquareImageView.kt, app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt, app/src/main/res/layout/recycler_item_saved_clipart.xml
Fixes #409
Changes:
- Cliparts can now be deleted
Saved Cliparts:
After Delete:
Changed Cliparts:
=> feat: ability to delete cliparts

app/src/main/java/org/fossasia/badgemagic/ui/custom/DrawBadgeLayout.kt
Fixes #423
Changes: Added conditions for checking for the indexOutOfBoundException.
=> fix: indexOutOfBounds exception in drawlayout

scripts/upload-apk.sh
=> fix: Use correct AAB and APK filenames

scripts/upload-apk.sh
Changes: 
- Updated Upload Script
=> chore: update upload script

versions.gradle
=> build(deps): updated kotlin version

app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
Fixes #356 
Changes:
- The app now automatically detects if it should add a line infront of the badge or not
=> fix: invert LED bug

app/build.gradle
Fixes #451 
Changes: 
- updated build version
=> chore: updated build version to 1.4.0

.travis.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt, app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt, app/src/main/java/org/fossasia/badgemagic/bindings/EditBadgeViewBindings.kt, app/src/main/java/org/fossasia/badgemagic/database/ClipArtService.kt, app/src/main/java/org/fossasia/badgemagic/di/Modules.kt, app/src/main/java/org/fossasia/badgemagic/ui/EditClipartActivity.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedClipartFragment.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/java/org/fossasia/badgemagic/util/Converters.kt, app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/EditClipartViewModel.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt, app/src/main/res/layout/activity_edit_clipart.xml, app/src/main/res/layout/recycler_item_saved_clipart.xml, build.gradle, versions.gradle
Fixes #449 
Changes: 
- release 1.4.0
=> chore: release 1.4.0

app/src/main/java/org/fossasia/badgemagic/viewmodels/DrawViewModel.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/EditBadgeViewModel.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/EditClipartViewModel.kt
Fixes #466 
Changes:
- default value for draw is now true
=> feat: Preselect "Draw" when going to draw screen

.travis.yml, docs/sources/Makefile, docs/sources/conf.py, docs/sources/index.rst, docs/sources/make.bat, scripts/upload-gh-pages.sh
=> feat: prepare gh-pages on branch push

app/src/main/java/org/fossasia/badgemagic/viewmodels/DrawViewModel.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/EditBadgeViewModel.kt, app/src/main/java/org/fossasia/badgemagic/viewmodels/EditClipartViewModel.kt
Fixes #480 
Changes: 
- fixed draw mode enum
=> fix: Draw Clipart Screen - Cannot draw

.travis.yml
Fixes #492 
Changes: 
- enabled bundler
=> chore : enabling bundler caching

.travis.yml
Fixes #500 
Changes:
- added repo condition in travis
=> chore: fix deploy in forks

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> feat: support for android 10

app/src/main/java/org/fossasia/badgemagic/adapter/DrawableItemHolder.kt, app/src/main/java/org/fossasia/badgemagic/adapter/ModeItemHolder.kt, app/src/main/java/org/fossasia/badgemagic/adapter/SaveAdapter.kt, app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsViewHolder.kt
=> fix: deprecated context calls

app/src/main/AndroidManifest.xml
=> fix: privacy storage access crash

app/build.gradle, fastlane/metadata/android/en-US/changelogs/8.txt
=> chore: update build number for release 1.6.0

fastlane/Fastfile
=> fix: Release aab path

scripts/upload-apk.sh
=> chore: fail script when deployment not successful

app/src/main/AndroidManifest.xml, app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
=> chore: improve storage utils and remove requestLegacyStorage

app/src/main/java/org/fossasia/badgemagic/util/Converters.kt
=> fix: support non latin languages

app/src/main/res/layout/fragment_about_us.xml, app/src/main/res/values/dimens.xml
=> feat: Improve AboutUs

app/src/main/java/org/fossasia/badgemagic/util/StorageUtils.kt
=> chore: refactor StorageUtils

app/src/main/java/org/fossasia/badgemagic/adapter/SavedClipartsAdapter.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt, app/src/main/res/drawable/ic_delete_black_24dp.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Fixes #589 
Badge Deletion
Clipart Deletion.
=> feat: Add AlertWarning for deleting badges and cliparts

app/src/main/java/org/fossasia/badgemagic/adapter/SaveAdapter.kt, app/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt, app/src/main/res/drawable/ic_import_export_black_24dp.xml, app/src/main/res/drawable/ic_send_black_24dp.xml, app/src/main/res/layout-land/recycler_save_item.xml, app/src/main/res/layout/recycler_save_item.xml
=> fix: Improve and Fix Saved Badge

.travis.yml, scripts/upload-ios-framework.sh
=> fix: ios-framework build

scripts/upload-apk.sh
=> chore: fix upload script with android

android/build.gradle, build.gradle
=> chore(deps): bump com.diffplug.gradle.spotless from 3.26.1 to 3.27.0

.travis.yml, BadgeMagicModule/build.gradle.kts
=> fix: ios-framework deploy

android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt, android/src/main/res/drawable/ic_star.xml, android/src/main/res/menu/drawer_items.xml, android/src/main/res/values-zh-rCN/strings.xml, android/src/main/res/values/strings.xml
Fixes #621
Screenshot:
Changes: 
Added rate us menu on navigation drawer. 
On click it will open our application playstore page. Where user can rate application and provide feedback.
=> feat: Rate application feature so that users can rate app and provide feedback.

android/src/main/java/org/fossasia/badgemagic/bindings/SettingsViewBindings.kt, android/src/main/java/org/fossasia/badgemagic/core/bluetooth/Constants.kt, android/src/main/java/org/fossasia/badgemagic/core/bluetooth/GattClient.kt, android/src/main/java/org/fossasia/badgemagic/core/bluetooth/ScanHelper.kt, android/src/main/java/org/fossasia/badgemagic/data/badge/Badges.kt, android/src/main/java/org/fossasia/badgemagic/data/badge/DeviceID.kt, android/src/main/java/org/fossasia/badgemagic/di/Modules.kt, android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt, android/src/main/java/org/fossasia/badgemagic/ui/EditBadgeActivity.kt, android/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt, android/src/main/java/org/fossasia/badgemagic/util/BadgeUtils.kt, android/src/main/java/org/fossasia/badgemagic/util/PreferenceUtils.kt, android/src/main/java/org/fossasia/badgemagic/viewmodels/SettingsViewModel.kt, android/src/main/res/layout/fragment_settings.xml, android/src/main/res/values-zh-rCN/strings.xml, android/src/main/res/values/strings.xml
=> feat: [Android] allow users to use other badges

android/src/main/java/org/fossasia/badgemagic/ui/DrawerActivity.kt
=> feat: Add animation while transition

.gitignore, .travis.yml, iOS/badgemagic.xcodeproj/project.pbxproj
=> chore: [iOS] framework builds should be independent

android/src/main/java/org/fossasia/badgemagic/ui/fragments/SavedBadgesFragment.kt, android/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt, android/src/main/res/drawable/ic_empty_list.xml, android/src/main/res/layout-land/fragment_main_save.xml, android/src/main/res/layout/fragment_main_save.xml, android/src/main/res/layout/fragment_saved_cliparts.xml, android/src/main/res/values-land/dimens.xml, android/src/main/res/values-zh-rCN/strings.xml, android/src/main/res/values/dimens.xml, android/src/main/res/values/strings.xml
=> feat: icon when saved clipart or saved list is empty

android/src/main/java/org/fossasia/badgemagic/ui/fragments/SettingsFragment.kt, android/src/main/java/org/fossasia/badgemagic/viewmodels/SavedClipartViewModel.kt
=> fix: app crashes

android/build.gradle, fastlane/metadata/android/en-US/changelogs/9.txt
=> chore: updated version name to 1.7.0
